package com.team.killskills.nukvoy_android.model;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.ForeignKey;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.PrimaryKey;
import android.support.annotation.NonNull;

import com.team.killskills.nukvoy_android.dto.RouteDto;

/*
Annotate the class with @Entity and use the tableName property to set the name of the table.
*/

@Entity
public class Route {

    /*Set the primary key by adding the @PrimaryKey annotation to the correct fields — in our case, this is the ID of the Route, and the id is autogenerated.*/

    @PrimaryKey(autoGenerate = true)
    public int id;
    @NonNull
    public String iataCode;
    @NonNull
    public String destination;

    public Route() {
    }

    //Constructor
    public Route(@NonNull String IataCode, RouteDto routeDto){
        iataCode = IataCode;
        destination = routeDto.destination;
    }
}
